---
title: "Q2"
output: html_document
---

```{r setup, include=TRUE}
# This block sets up your global options
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

x1 <- 1; y1 <- 2
x2 <- 3; y2 <- 8

# Slope
m <- (y2 - y1) / (x2 - x1)
m

# Intercept
b <- y1 - m * x1
b

# Equation display (forces visible output)
cat("Equation: y =", m, "x +", b, "\n")

# Intercepts
x_intercept <- -b / m

cat("X-intercept:", x_intercept, "\n")
cat("Y-intercept:", b, "\n")

x_q2 <- c(3, 5, 6, 8, 9, 11)
y_q2 <- c(2, 3, 4, 6, 5, 8)

data_q2 <- data.frame(x_q2, y_q2)

# Summary stats (forces HTML output like your FA14 file)
summary(data_q2)

# Regression model
model2 <- lm(y_q2 ~ x_q2, data = data_q2)
summary(model2)

algebra <- c(75, 80, 93, 65, 87, 71, 98, 68, 84, 77)
physics <- c(82, 78, 86, 72, 91, 80, 95, 72, 89, 74)

data3 <- data.frame(algebra, physics)

# MUST produce plot output (prevents blank HTML)
plot(data3$algebra, data3$physics,
     main = "Algebra vs Physics Grades",
     pch = 19)

# Model
model3 <- lm(physics ~ algebra, data = data3)
summary(model3)

# Prediction
p_grade <- predict(model3, newdata = data.frame(algebra = 75))
cat("Predicted Physics (75 Algebra):", p_grade, "\n")

# Reverse regression
model3_inv <- lm(algebra ~ physics, data = data3)
p_alg <- predict(model3_inv, newdata = data.frame(physics = 95))
cat("Predicted Algebra (95 Physics):", p_alg, "\n")

x_q4 <- 0:6
y_q4 <- c(2.4, 2.1, 3.2, 5.6, 9.3, 14.6, 21.9)

data4 <- data.frame(x_q4, y_q4)

# Model
model4 <- lm(y_q4 ~ x_q4 + I(x_q4^2), data = data4)
summary(model4)

# Prediction (must use correct data frame column name)
pred_7 <- predict(model4, newdata = data.frame(x_q4 = 7))
cat("Predicted Y at X=7:", pred_7, "\n")

